In [2]:
from PIL import Image
from numpy import array

In [3]:
img = Image.open('Tanjiro.jpg')
img2arr = array(img)
print(img2arr)

[[[ 62  42 153]
  [ 58  38 149]
  [ 56  36 147]
  ...
  [108  74 246]
  [123  88 253]
  [139 104 255]]

 [[ 65  45 156]
  [ 61  41 152]
  [ 60  40 151]
  ...
  [100  66 238]
  [111  76 241]
  [125  90 254]]

 [[ 67  47 158]
  [ 64  44 155]
  [ 63  43 154]
  ...
  [ 98  62 234]
  [104  68 236]
  [117  80 246]]

 ...

 [[ 14   6  45]
  [ 14   6  45]
  [ 14   6  45]
  ...
  [ 15   4  44]
  [ 15   4  44]
  [ 16   6  43]]

 [[ 14   6  45]
  [ 14   6  45]
  [ 14   6  45]
  ...
  [ 14   3  43]
  [ 15   4  44]
  [ 15   5  42]]

 [[ 14   6  45]
  [ 14   6  45]
  [ 14   6  45]
  ...
  [ 15   4  44]
  [ 15   4  44]
  [ 16   6  43]]]


In [4]:
arr2im = Image.fromarray(img2arr)

In [5]:
arr2im.show()